import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/shared/components/providers/AuthProvider";
import { QueryProvider } from "@/shared/components/providers/QueryProvider";

const roboto = Roboto({
    subsets: ["cyrillic"],
});

export const metadata: Metadata = {
    title: "Mindset",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={roboto.className}>
            <body className="bg-black">
                <QueryProvider>
                    <AuthProvider>{children}</AuthProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
