import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Container from "@/components/Container/Container";
import CustomCursor from "@/components/CustomCursor/CustomCursor";
import QueryProvider from "@/components/QueryProvider";

const mulish = Mulish({
    subsets: ["cyrillic"],
});

export const metadata: Metadata = {
    title: "Mindset",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={mulish.className}>
            <body>
                <QueryProvider>
                    <CustomCursor />
                    <Header />
                    <Container>{children}</Container>
                    <Footer />
                </QueryProvider>
            </body>
        </html>
    );
}
