import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Container from "@/components/Container/Container";

export const metadata: Metadata = {
    title: "Mindset",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body>
                <Header />
                <Container>{children}</Container>
                <Footer />
            </body>
        </html>
    );
}
